version: '3.8'
services:
  # Database
  postgres:
    container_name: eatnet-postgres-test
    build: ./postgres
    environment:
      POSTGRES_USER: SET_YOUR_USER
      POSTGRES_PASSWORD: SET_YOUR_PASSWORD
      POSTGRES_URL: postgres://SET_YOUR_USER:SET_YOUR_PASSWORD@localhost:5432/eatnet-test
      POSTGRES_DB: eatnet-test
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
  
  # pgAdmin
  pgadmin:
      image: dpage/pgadmin4
      environment: 
          - PGADMIN_DEFAULT_EMAIL=SET_YOUR_PGADMIN_EMAIL@mail.com
          - PGADMIN_DEFAULT_PASSWORD=SET_YOUR_PGADMIN_PASSWORD
      ports: 
          - "5050:80"
  
  # Redis
  redis:
    container_name: eatnet-redis
    image: redis
    ports:
      - "6379:6379"

  # Backend
  api:
    container_name: eatnet-api-test
    build:
      context: ./api/
      dockerfile: Dockerfile.dev
    command: npm start
    working_dir: /usr/src/eatnet-api
    volumes:
      - ./api:/usr/src/eatnet-api
      - ./api/uploads:/usr/src/eatnet-api/uploads
    expose: 
      - 3000
    environment:
      POSTGRES_URI: postgres://SET_YOUR_USER:SET_YOUR_PASSWORD@postgres:5432/eatnet-test
      REDIS_URI: redis://eatnet-redis:6379
      API_URL: SET_API_URL
      KNEX_CONFIG: development
      API_PORT: 3000
      PLANTNET_API_URL: https://my-api.plantnet.org/v2/identify
      PLANTNET_APIKEY: SET_PLANTNET_APIKEY
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - api