FROM node:16.12.0

# Create app directory
RUN mkdir -p /usr/src/eatnet-api
WORKDIR /usr/src/eatnet-api

# Install app dependencies
COPY package.json /usr/src/eatnet-api

# Bundle app source
COPY . /usr/src/eatnet-api
RUN npm install

# Build arguments
ARG NODE_VERSION=16.12.0

# Environment
ENV NODE_VERSION $NODE_VERSION